### ISSUE TITLE
Feature request: shortcut friendly

### ISSUE THREAD

**Issue by kupiqu** [rogerbramon/getTV3Videos#1]
Very useful webpage but it requires of multiple manual steps:

1- find video on ccma and copy video identifier
2- go manually to http://videostv3.herokuapp.com or find it in the bookmarks and click
3- mouse click on search bar to get focus and paste the video identifier
4- manually click on 'Buscar' button
5- finally, right click to download on the video link according to preferred quality from the ones available

Although step 1 is not specific of getTV3Videos and step 5 I think it's fine, it would be fantastic to automatize steps 2 to 4 in a shortcut friendly fashion.

This would be possible if one could write an url such as http://videostv3.herokuapp.com/video_id and go directly to step 5 from step 1. 

If this feature would be supported, one could then define a shorcut in the browser, such as 'tv3', so from step 1 one would go directly to step 5 by using only the keyboard in the following way:
- open new tab: ctrl+t
- write shorcut, paste the video_id and press return: tv3 ctrl+v

**Comment by siknus** [comment]
kupiqu, you might like this bookmarklet: 
https://github.com/icon42/descarrega-videos-tv3

**Comment by kupiqu** [comment]
Hey, thank you. It works great!

**Comment by rogerbramon** [comment]
PR #4 adds this feature. Now you can use `/video/video_id` to go directly to the video.
e.g. https://get-tv-3-videos-git-migrate-nextjs.rogerbramon.vercel.app/video/5851449

Any feedback is appreciated.
