### ISSUE TITLE
Descarregar tv3 des de Alemanya

### ISSUE THREAD

**Issue by luciangrec** [rogerbramon/getTV3Videos#11]
Hola Roger,

Estic aprenent el catala vivint amb la meva parella catalana a alemanya i m'agradaria descarregar videos que no es puguin veure des d'aqui, nomes des de Espanya. He vist que a espanya no hi ha cap problema per descarregar-los pero des de aqui em sembla que no funciona "403 Forbidden". Hi ha una possibilitat per poder fer servir la teva pagina des d'aqui tambe?
Pardo pel spam pero no tinc compte de Twitter

Gracies
Lucian

**Comment by Peiprjs** [comment]
Hola Lucian,

Aquest problema que tens és impossible de solucionar. Si no entenc malament, la CDN de TV3, que és la xarxa de servidors que distribueix els vídeos està limitada a Catalunya. El que podries fer és demanar a algú de Catalunya que ho descarregui o mirar-ho per Youtube, hi ha alguns programes.

**Comment by rogerbramon** [comment]
Hola @luciangrec, perdona per no haver contestat. En @Peiprjs té raó. Una opció que suposo que podria funcionar és que fessis servir una VPN per simular que estàs a territori espanyol. 

Roger

**Comment by luciangrec** [comment]
Hola,
Gracies per les repostes pero ja no cal. Ens hem mudat a Barcelona finalment i aqui hi ha mes de catalanitat diguem. Us puc convida a un cafe si voleu haha, he vist que en @Peiprjs es apasionat de cuets. Jo vaig treballar per una empresa de cuets a Alemanya de fet. Et podria posar en contacte amb algu d'alla si t'interessa tot i que no se quin es el teu perfil i els teus interessuos en concret.
En tot cas merci per haver-me contestat

**Comment by Peiprjs** [comment]
Hola,
Gràcies per l'oferta, m'encantaria!
