### ISSUE TITLE
Falla a la majoria de programes del super3

### ISSUE THREAD

**Issue by lepalom** [rogerbramon/getTV3Videos#2]
Per exemple:

https://www.ccma.cat/tv3/super3/germans-kratt/lexterminiador/video/5754686/

no troba el vídeo malgrat que hi és. Ho podeu revisar si us plau?

**Comment by rogerbramon** [comment]
Hola @lepalom,

El vídeo que has passat d'exemple ha estat ja despublicat. Només funciona amb els vídeos que estan disponibles a la carta en el moment de la descàrrega.

Per exemple, aquest vídeo m'ha funcionat correctament: https://www.ccma.cat/tv3/super3/germans-kratt/aventura-allucinant-a-lamazonia-2a-part/video/6037778/ però només funcionarà fins el dia 19 tal i com diu la pàgina del capítol.

**Comment by lepalom** [comment]
Hola @rogerbramon,

quan ho vaig provar no va funcionar i estava disponible. Ara ho revisaré perquè no trobo un contraexemple. No tanquis el tiquet per ara si us plau a veure el què.

**Comment by rogerbramon** [comment]
Hola @lepalom,

Has trobat algun exemple? Sinó preferiria tancar el tiquet i el reobres si en algun moment et passa. 

Merci

**Comment by rogerbramon** [comment]
Crec que he trobat un exemple del que deies: https://www.ccma.cat/tv3/super3/bob-el-manetes-cap-13-pallissa-en-reparacio/bob-el-manetes-cap-13-pallissa-en-reparacio/video/fitxa-programa/3421850/3421850/

Està arreglat al PR #8. Pots fer servir la nova versió que he publicat a https://videostv3.vercel.app/

**Comment by lepalom** [comment]
Moltes gràcies!!!!
