### ISSUE TITLE
Subtitles not available

### ISSUE THREAD

**Issue by miquelbofill** [rogerbramon/getTV3Videos#20]
Hi Roger,

I've been trying to download some video as well as its subtitles, e.g. from [https://www.ccma.cat/tv3/alacarta/inedits/inedits-kirk-douglas/video/6105751/](https://www.ccma.cat/tv3/alacarta/inedits/inedits-kirk-douglas/video/6105751/), but subtitles are not available to download, although there are available when playing the video on the TV3 website.

Are you aware of this issue?

Best,
Miquel

**Comment by rogerbramon** [comment]
Hi @miquelbofill!

Thanks for contacting. I guess you refer to the old version (http://videostv3.herokuapp.com). Try using the new one, it seems to me subtitles are available ([](https://videostv3.vercel.app/video/6105751))

**Comment by miquelbofill** [comment]
Thanks @rogerbramon, I wasn't aware of the new version.

Cheers,
Miquel
