### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by drguell** [rogerbramon/getTV3Videos#27]
Hi,

I tried to download English subtitles but only appears Catalan ones.

I think that you don't use correctly all the array to extract all the availables languages.

Thanks!

**Comment by rogerbramon** [comment]
Thanks @drguell. Do you have an example to take a look?

**Comment by drguell** [comment]
For example for this URL:

https://www.ccma.cat/tv3/alacarta/crims/isidre/video/6157454/

![imagen](https://user-images.githubusercontent.com/88421735/168005157-dd5b1a40-8cde-4ee2-8392-a1c18be40f9c.png)

But if you see the complete JSON, there are all the subtitles:

http://dinamics.ccma.cat/pvideo/media.jsp?media=video&version=0s&idint=6157454

I use to test this website: https://videostv3.vercel.app/ , isn't this?

**Comment by rogerbramon** [comment]
It should work now, it's a cache issue. I'll make a change to fix it. Let me know if you still experience the problem.
Thanks.
