### ISSUE TITLE
No parseig dels media en algun cas

### ISSUE THREAD

**Issue by srafols** [rogerbramon/getTV3Videos#3]
Hola,

Hi ha algun vídeo en que les dades del json de resposta el camp **media** és un objecte i no un array, com passa amb el següent vídeo (http://dinamics.ccma.cat/pvideo/media.jsp?media=video&version=0s&idint=2837690), cosa que fa que no es parsegi correctament la resposta i surti el missage de que el vídeo no existeix.

![image](https://user-images.githubusercontent.com/2260652/84568375-5fec6080-ad7f-11ea-9696-cedcaaa3c60f.png)

![image](https://user-images.githubusercontent.com/2260652/84568301-be650f00-ad7e-11ea-8a85-359c5715aeaf.png)

En la gran totalitat dels vídeos publicats el format és el següent, i el format que parseja correctament l'aplicació.

http://dinamics.ccma.cat/pvideo/media.jsp?media=video&version=0s&idint=6047435

![image](https://user-images.githubusercontent.com/2260652/84568340-0f750300-ad7f-11ea-8efa-532da483de1a.png)

Diria és un cas mot puntual. En tot cas, gràcies per la web.

**Comment by rogerbramon** [comment]
Merci @srafols, estic preparant una nova versió que ho tindrà arreglat.

**Comment by rogerbramon** [comment]
#4 ho arregla. 

Link del vídeo que has posat d'exemple: https://get-tv-3-videos-git-migrate-nextjs.rogerbramon.vercel.app/video/2837690

**Comment by srafols** [comment]
Perfecte. Gràcies pe la nova versió @rogerbramon.
