### ISSUE TITLE
Descarregar a 1080p

### ISSUE THREAD

**Issue by adocampo** [rogerbramon/getTV3Videos#35]
Hola!

Menuda peça d'art has desenvolupat! Volia tindre al meu Plex Crims i no ho trobava enlloc. Gràcies a tu ja els tinc al meu servidor :)
M'he adonat, però, que només els puc descarregar a 720p, i a la mateixa web els puc veure a 1080p.
És algun tipus de limitació? 

Salutacions i moltes gràcies per aquesta meravellosa eina!

**Comment by rogerbramon** [comment]
Hola @adocampo! Gràcies pels teus compliments! 😊

Doncs la veritat és que encara que digui 720p la descàrrega és de 1080p. Fa un parell d'anys oferien com a màxim 720p, i al passar a 1080p ho continuen anunciant com a 720p. Si vols ho pots confirmar, mirant la resolució dels vídeos hauria de sortir 1920x1080.

Suposo que el que hauré de fer és posar Alta i Mitja resolució així no hi haurà aquesta confusió. O veure si hi ha alguna altra manera d'obtenir la qualitat real.

Merci!

**Comment by adocampo** [comment]
Ostres, és veritat, apareix com 1080p... no he dit res llavors :P

![imagen](https://user-images.githubusercontent.com/2266612/201991823-aa3c32c9-1fa6-417a-9cff-99c24a7784af.png)
Lo que ara que em fixo, el plex diu que està en anglés... això és merament cosmètic, ja que no filtro per idiomes, però suposo que com plex extreu la informació de la metadata del fitxer, estarà en blanc i posarà anglés per defecte, no?

**Comment by adocampo** [comment]
> Suposo que el que hauré de fer és posar Alta i Mitja resolució així no hi haurà aquesta confusió. O veure si hi ha alguna altra manera d'obtenir la qualitat real.

Per cert, hi ofereixen tres qualitats, almenys en crims, no sé la resta, SD, HD i FHD. Jo m'ho descarrego tot en el més alt que puc, perquè només ho veig a la TV, i suposo que tothom que trobi getTV3Videos voldrà la màxima qualitat, però potser a algú li interessa en SD per veure-ho al mòbil.

**Comment by rogerbramon** [comment]
El que preguntes de l'idioma, no ho sé. Possiblement és el que comentes.

Amb l'API que faig servir jo històricament només han ofert dues qualitats que cada vegada han sigut més altes. A la web de TV3 fa un temps que ja no fan servir aquest sistema, sinó un sistema adaptatiu que descarrega el vídeo per segments allà potser sí que ofereixen 3 qualitats.
