### ISSUE TITLE
Suport de 1080p

### ISSUE THREAD

**Issue by CarlesLlobet** [rogerbramon/getTV3Videos#43]
Bones!

Primer de tot, gràcies per la feina 💪 🎉 

M'he fixat que la majoria de videos de TV3 A la carta suporten 1080p en el reproductor (a part de 720 y 480).
Tot i així, aquesta eina nomes els pot descarregar en 720 o 480.

M'he estat mirant el codi per si podia fer una PR ràpida i arreglar-ho, pero ja he vist que l'API de https://dinamics.ccma.cat/ directament nomès retorna els formats en 720p i 420p.

Obro l'Issue per veure si es podria trobar algun altre manera per a descarregar els videos en millor qualitat.

Gràcies!

**Comment by rogerbramon** [comment]
Gràcies @CarlesLlobet, sí es un tema de l'API, però en realitat la descarrega sí que és 1080p però l'etiqueten com a 720. És una pregunta que rebo recurrentment (#35).

[Fa un temps m'ho vaig mirar](https://twitter.com/rogerbramon/status/1293216432893853696), sembla que ara fan servir un altre sistema que fa descarregant trossets de vídeo així es poden adaptar a les condicions de la xarxa i mida de pantalla. 

No sé si hi ha enlloca una manera de tenir tot el vídeo, sinó és complicat perquè hauríem de descarregar tots els trossets i ajuntar-los.

Qualsevol idea és benvinguda. :)

Salut

**Comment by CarlesLlobet** [comment]
Bones Roger,

Gràcies per la ràpida resposta. Si, jo tambe vaig estar mirant el sistema que fan servir descarregant troçets de m4s, i sembla que ni tan sols amb sistemes com [Video DownloadHelper](https://chrome.google.com/webstore/detail/video-downloadhelper/lmjnegcaeklhafolokijcfjliaokphfk?hl=en-GB) el detecta correctament.

De totes formes, si em comentes que tot i etiquetar-ho com a 720p, els videos descarregats son en 1080p, suposo que no val la pena mirar-s'ho més 👍  
Tanco l'issue doncs 💪
