### ISSUE TITLE
Enllaç que no funciona

### ISSUE THREAD

**Issue by lepalom** [rogerbramon/getTV3Videos#44]
Aquest enllaç no dona cap vídeo, però quan el cliques sí.

https://www.ccma.cat/tv3/sx3/la-cinglera-dels-esperits/video/6125524/ 

Per altra banda, també tens l'opció de visualitzar a 1080 però no apareix com a opció. Seria possible afegir-ho?

**Comment by rogerbramon** [comment]
Hola @lepalom, a mi em funciona. Potser va fallar temporalment.

Respecte a 1080, és un problema de com dona la informació TV3, en realitat ja és 1080. Per més info #43
