### ISSUE TITLE
URL de vídeos despublicats

### ISSUE THREAD

**Issue by josepmaria79** [rogerbramon/getTV3Videos#47]
Benvolgut Roger,

M'he adonat que una vegada un vídeo ha estat despublicat, la URL a l'arxiu MP4 segueix vigent al servidor.

És possible obtenir l'enllaç a l'arxiu MP4 a partir d'algun identificador tot i que el codi de la pàgina on està despublicat no hi porti?

**Comment by rogerbramon** [comment]
Hola Josep Maria,

No que jo sàpiga. Si no te l'has guardat abans no sé com trobar-la. Si ho descobreixo ho publicaré.

**Comment by josepmaria79** [comment]
Moltes gràcies! A veure si hi ha sort i ho esbrinem...El dia 18 març 2024 11:28, Roger Bramon ***@***.***> va escriure:
Hola Josep Maria,
No que jo sàpiga. Si no te l'has guardat abans no sé com trobar-la. Si ho descobreixo ho publicaré.
