### ISSUE TITLE
Links que no troba l'MP4 - Exemple

### ISSUE THREAD

**Issue by ElectricSea** [rogerbramon/getTV3Videos#50]
Hola Roger! Abans que res enhorabona pel codi. Des de feia setmanes intentava poder tornar a descarregar contingut des de TV3 i no hi havia manera. Qui té nens petits i vol que vegi contingut en català lliure d'anuncis ja sap del que parlo i valorarà com es mereix el teu codi! ;)

Doncs m'he trobat que hi ha enllaços com aquest que no és capaç de trobar l'MP4 original. Perquè ho tinguis en compte: 

https://videostv3.vercel.app/video/6305017

Merci!

Guillem

**Comment by rogerbramon** [comment]
Gràcies Guillem! Ja està arreglat!

Salut!

**Comment by ElectricSea** [comment]
De res!  A tu Roger per la ràpida resposta!


Salutacions,

Guillem Gandol
***@***.***
@electricsea
